### ISSUE TITLE
Scalability clarification

### ISSUE THREAD

**Issue by grotsev** [diogob/postgres-websockets#25]
As I understand #9, the project is more ready for production today. I've not found visible bottleneck while my shallow dive into code. My assumption is that Multiplexor can handle many thousands of websocket clients for a channel.
But situation when every client has own channel is not optimal. PostgREST-WS hold one connection subscribed to many channels in PostgrSQL. And PostgreSQL have to do redundant job to route all channels to PostgREST-WS. Performance impact of this is unclear.
We can move all routing to Multiplexor by subscribing to one channel in PostgreSQL and passing real channel name in message payload. This implementation may be in another URI endpoint.

Have you any idea for outlined or another scalability bottlenecks?

**Comment by diogob** [comment]
@grotsev good point. I haven't done much testing since the earlier benchmarks outlined here: https://github.com/begriffs/postgrest/pull/872

Move all the routing to the Multiplexer might be a good idea. I'd love to have some solid benchmarks before doing that move though.

**Comment by grotsev** [comment]
I'm going to explore PostgreSQL notify implementation and benchmarks in mid term future.

**Comment by grotsev** [comment]
Some thoughts:
1. Notification payload should be JSON serialized. It is extensible envelope for future enhancements and PostgreSQL has great support for it.
2. Client may have more complex destination address and message may be send from complex source address. Routing interface should be quite abstract to support these source and destination description:
2.0. Exact match (source _abc_ matches destination _abc_ only).
2.1. Fan out by prefix (source _a*_ matches destination _abc_).
2.2. Fan in by prefix (source _abc_ matches destination _a*_)
2.3. Union (source _a|b_ matches destination _b|c_)
2.4. Combination of them which may be efficiently implemented by some trie-like structure.

**Comment by diogob** [comment]
@grotsev check the PR #33 

I won't implement any routing logic in this PR since my immediate concern is to get rid of the defect described in #32 (preserving equivalent functionality).

Right now any complex routing can be implemented with some listener on the database side. It could be easily done with a PostgreSQL function in conjunction with something like https://github.com/diogob/pg-recorder

**Comment by grotsev** [comment]
@diogob You are right. Routing is not part of this PR and it closes #25 and #32. My point is that client may describe its address in some language not just flat channel name, similar to URL filtering and ordering in PostgREST. But it is subject of some another issue concerning [relayMessages](https://github.com/diogob/postgres-websockets/blob/04d2dcf30522aa2c6bec8b606723ceea896597bd/src/PostgresWebsockets/Broadcast.hs#L52) implementation.

Thank you for pg-recorder. I was going to implement it by myselt but it is already here! It would be great to see in PostgREST [ecosystem](https://postgrest.com/en/v4.3/intro.html#ecosystem). If your are interesting in this ecosystem there is [http_port](https://github.com/grotsev/http_port) to async HTTP request from PostgreSQL.

**Comment by diogob** [comment]
@grotsev neat project the http_port! I'm adding to my tool box :D 
I just merged the PR and added some docker-compose instructions for a ready to use test server.
