### ISSUE TITLE
Error while startup

### ISSUE THREAD

**Issue by grotsev** [diogob/postgres-websockets#32]
Sometimes (~10% of runs) while startup console shows
```
Listening on port 3002
message type 0x43 arrived from server while idle
message type 0x5a arrived from server while idle
```

And then postgrest-websockets does not deliver messages.

**Comment by diogob** [comment]
@grotsev does this happens when messages arrive during the startup? After that are the messages being all delivered or there is message loss even after the startup?
Is there an easy way to reproduce?

**Comment by grotsev** [comment]
The [project](https://github.com/grotsev/scor-ng) is on github but it may be time consuming to reproduce.

I've tested several cases and find out that the error happens only while [line 19](https://github.com/grotsev/scor-ng/blob/master/bin/devserver#L19) is commented i.e. postgrest and postgrest-ws are starting concurrently, and client in browser is running. This client is smart enough to try exponential backoff reconnect to web socket. Client just listen and do not send. So there is no messages during startup.

After that db does notify but the message is lost.

**Comment by diogob** [comment]
Thanks for the bug report @grotsev 

I have investigated a bit the issue, it seems to be related to how the same libpq connection reference  is being used concurrently in these error cases. It is hard to solve this problem keeping multiple database channels and only one listening connection.

The best approach seems to be issuing only one LISTEN command and loop forever keeping the listening connection exclusive for receiving notifications. In this case the Multiplexor would distribute messages to different channels as suggested in #25 

I'll open a pull request as soon as I can have a good working draft.
