### ISSUE TITLE
chrome error

### ISSUE THREAD

**Issue by ajayashuba** [diogob/postgres-websockets#42]
why do i get this message while closing websocket in chrome ```failed: Invalid frame header```

**Comment by ajayashuba** [comment]
https://imgur.com/PppPZ8C

**Comment by ajayashuba** [comment]
i have frames data as (Opcode-1) with length 20

**Comment by ajayashuba** [comment]
https://stackoverflow.com/questions/40498032/websocket-server-sending-text-frames-to-client

**Comment by diogob** [comment]
Sorry for the delay. Do you have any issues closing the websocket, or reopening it?
I'm not handling the connection closing in my code, so I'd have to look in an underlying library. 
If you could send a more detailed transcript of the interactions between your code and the socket I'd be glad to help troubleshooting.

**Comment by ajayashuba** [comment]
i get this message only when closing connection it get closed but in chrome it get this message ```failed: Invalid frame header``` in mozilla its fine..

**Comment by ajayashuba** [comment]
i am just giving normal ```WebSocket.close()``` ; it works but the console gives error as i mentioned above .the error occurs only in chrome and i also told you the red highlighted frame data i receive as ```opcode1``` ;many ppl also get the same error with websocket .. also i shared you a stackoverflow link dont know if that is the right link ..pls look into it

**Comment by diogob** [comment]
I don't know exactly in which cases this problem happens therefore I'm having a hard time reproducing the issue to come up with a fix. If you are future reader and you are having this issue please reopen the issue and help me to understand what exactly happens
