### ISSUE TITLE
Feature Request: @filename support for PGWS_DB_URI environment variable

### ISSUE THREAD

**Issue by W1M0R** [diogob/postgres-websockets#63]
The `PGWS_JWT_SECRET` environment variable already supports values using the @filename format, which is very useful for passing in Docker secrets, e.g. `PGWS_JWT_SECRET="@/run/secrets/my_jwt_secret_key"`.

Since the postgres connection URI often includes a password in plain text, it would be great if the connection URI could be specified in a secret managed by Docker, that could then be provided to postgres-websockets in a similar way, e.g. `PGWS_DB_URI: "@/run/secrets/my_db_uri"`.

**Comment by diogob** [comment]
@W1M0R the latest 0.9.0.0 release should take care of this issue, please verify and close the issue if that solves your use case

**Comment by W1M0R** [comment]
Thanks! I'll check it out.

**Comment by W1M0R** [comment]
Works as advertised. Thanks @diogob!
