### ISSUE TITLE
Feature Request: configurable retry attempts for Docker container that exits with error code

### ISSUE THREAD

**Issue by W1M0R** [diogob/postgres-websockets#64]
Currently, a postgres-websockets Docker container will try to connect to postgres, and will retry until it can successfully connect. When using the postgres-websockets container inside a Docker stack (within Docker Swarm), that feature makes it hard for swarm to detect connectivity issues (since the issue is masked by postgres-websockets) and therefore it won't recreate the container.

It would be great if the postgres-websockets container could be configured with an environment variable, e.g. PGWS_RETRIES=0, that would cause postgres-websockets to not retry, and then to exit with error code 1. In a Docker Swarm environment, swarm will detect the failure and recreate the container at the next opportune time.

**Comment by W1M0R** [comment]
Thank you for your interest in this issue.

Here is an extract of the current log output:

```
postgres-websockets 0.8.0.1 / Connects websockets to PostgreSQL asynchronous notifications.
Listening on port 3000
Error connecting notification listener to database: Just "could not translate host name \"postgres\" to address: Name does not resolve\n"
Error connecting notification listener to database: Just "could not translate host name \"postgres\" to address: Name does not resolve\n"
Error connecting notification listener to database: Just "could not translate host name \"postgres\" to address: Name does not resolve\n"
Error connecting notification listener to database: Just "could not connect to server: Connection refused\n\tIs the server running on host \"postgres\" (10.0.12.14) and accepting\n\tTCP/IP connections on port 5432?\n"
```

In summary, the `Error connecting notification listener to database` class of errors should terminate the application with an error code, if the configured number of retry attempts have been reached.

**Comment by diogob** [comment]
@W1M0R the latest 0.9.0.0 release should take care of this issue, please verify and close the issue if that solves your use case

**Comment by W1M0R** [comment]
Thanks! I'll check it out.

**Comment by W1M0R** [comment]
Works as advertised. Thanks @diogob!
