### ISSUE TITLE
PostGres WebSocket handsake via browser

### ISSUE THREAD

**Issue by VYadav123** [diogob/postgres-websockets#70]
Hi, 
Our PostgresSQL is configured using JWT token, Our application is configured on Port 3000 successfully.
Now as per our requirement we need to listen the notifications generated whenever new entry comes into the table present in PostgSQL, so till now we successfully listen the Port 3000 using Putty
Now we want to listen the same port via browser, so for this we have tried below
![image](https://user-images.githubusercontent.com/77671088/105035296-c5749e00-5a80-11eb-8932-47063c4bff33.png)

but we are not getting notifications generated in PostgSQL
some of the imp points
1. PostgSQL is configured with JWT token
2. "events" channel is created on DB
3. Can see the notifications at PGadmin screen

**Comment by diogob** [comment]
Hi @VYadav123 , how are the notifications being generated? 
Could you post some code transcripts? Also what is the value of `PGWS_LISTEN_CHANNEL` ?
Note that you have to use the json format [described in the README](https://github.com/diogob/postgres-websockets#sending-messages-to-the-browser) to allow the message to be relayed by the postgres-websockets server.

**Comment by girishvenkata14** [comment]
Hi @diogob,

Below is the code snippet used:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/77968207/105711520-abcecd00-5f3e-11eb-8842-3ce83746dc90.png)

When we subscribe to the channel 'chat' through the browser, function PGWS_LISTEN_CHANNEL is returning blank.
Please suggest where we are going wrong.

**Comment by diogob** [comment]
`PGWS_LISTEN_CHANNEL` should be set to `events` or you should change your code to use the default channel name which is `postgres-websockets-listener`.
