### ISSUE TITLE
WebSocket stops receiving messages from the database

### ISSUE THREAD

**Issue by W1M0R** [diogob/postgres-websockets#71]
Quite regularly I have the situation where my application successfully connects to postgres-websockets, but without receiving any messages from the database. Restarting my application doesn't fix the problem. However, restarting postgres-websockets does fix the problem. I have been wanting to report this issue for a while now, but it is hard to provide relevant information for the issue. I wish I could somehow force postgres-websockets into this state, to make it easier to verify this issue. I couldn't find an option to enable debug logging in postgres-websockets. Here is my attempt at explaining the problem.

When this situation happened again today, instead of restarting postgres-websockets, I kept it running and continued to generate events from the database every few minutes. After a while, postgres-websockets started sending messages again to my application. 

This is what I think happened. My application had a successful WebSocket connection with postgres-websockets, and postgres-websockets in turn had a successful connection with postgres. In the early stages of the application, postgres-websockets had a working LISTEN session with postgres and successfully sent those messages along to my application. Then at some point, the LISTEN session between postgres-websockets and postgres became "invalid" (perhaps it died silently without notification from postgres). At some point, postgres-websockets reported ConnectionClosed in its log, and then after that my application could receive database messages again from postgres-websockets. 

For my application, it would be useful if postgres-websockets could detect this situation, and then try to re-establish a valid LISTEN session with postgres for that channel. If this fails, postgres-websockets should close connected WebSockets that are listening on that channel. 

@diogob Do you have any idea what might be happening? If you are stumped, then maybe my nginx proxy configuration is breaking things.

My postgres-websockets is configured as follows:

```bash
PGWS_DB_URI="@/run/secrets/postgres_db_uri"
PGWS_JWT_SECRET="@/run/secrets/jwt_key"
PGWS_LISTEN_CHANNEL="pgwebsockets"
PGWS_JWT_SECRET_BASE64="False"
PGWS_POOL_SIZE=10
PGWS_RETRIES="6"
```

This is how I send messages from Postgres:

```sql
  perform pg_notify('pgwebsockets', json_build_object(
    'channel', 'activities', 
    'payload', row_to_json(_activity_detail))::text);
```

My application connects to nginx, that then forwards requests to postgres-websockets. This is the relevant nginx configuration:

```nginx
    # see https://www.nginx.com/blog/websocket-nginx/
    location /ws {
      # drop /ws from the connection url, so that postgres-websockets doesn't interpret ws as the channel
      # our real channel is included in the JWT token
      rewrite /ws/(.*) /$1 break;
      proxy_pass $upstream_pgwebsockets;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }
```

This is what my application reports when successfully connected to postgres-websockets:

```
Connecting to WebSocket event source: ws://127.0.0.1:50630/ws/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtb2RlIjoicnciLCJjaGFubmVsIjoiYWN0aXZpdGllcyJ9.CWMLqg_sZd_xV6GcuVkq7JR7jMLgYDqLzEDqaEhbky4
Successfully connected to WebSocket event source.
Awaiting messages...
```

This is the postgres-websockets log during the state where my application is connected to it, but not receiving any messages sent by the database:

```
postgres-websockets 0.9.0.0 / Connects websockets to PostgreSQL asynchronous notifications.
Listening on port 3000
```

This is the postgres-websockets log during the state where my application started to receive messages sent by the database:

```
postgres-websockets 0.9.0.0 / Connects websockets to PostgreSQL asynchronous notifications.
Listening on port 3000
ConnectionClosed
```

This is the state of my Docker containers:

```
CONTAINER ID        IMAGE                                COMMAND
      CREATED             STATUS                  PORTS               NAMES
b77e421e63af        127.0.0.1:5000/pgwebsockets:fdtsdl   "/docker-entrypoint.…"   42 minutes ago      Up 41 minutes           3000/tcp            fdtsdl_pgwebsockets.1.kqe0qby0k96s9ca26uzb2s8qe
6193c6c39f2c        127.0.0.1:5000/postgres:fdtsdl       "docker-entrypoint.1…"   26 hours ago        Up 26 hours (healthy)   5432/tcp            fdtsdl_postgres.1.1mzwkxw4xner14fsufc7ubh5f
```

**Comment by diogob** [comment]
@W1M0R thanks for the detailed report. Perhaps the first step should be to create a debugging logger. It's a simple feature to implement and it would help to troubleshoot potential future issues as well.
Furthermore, your assessment of postgres-websockets losing the listen connection seems to be a good lead. If the situation happens again I would appreciate if you could inspect the results of `SELECT * FROM pg_stat_activity` and paste it here.

**Comment by W1M0R** [comment]
Thanks for your feedback @diogob. I'll try and get you the pg_stat_activity results.

**Comment by W1M0R** [comment]
@diogob Here is the result of `SELECT * FROM pg_stat_activity` when my application no longer receives data from postgres-websockets. When everything works as expected, this table has an additional row with a `query` value of `LISTEN pgwebsockets`.

```sql
 datid | datname |  pid  | usesysid | usename  | application_name | client_addr | client_hostname | client_port |         backend_start         |          xact_start          |          query_start          |         state_change          | wait_event_type |     wait_event      | state  | backend_xid | backend_xmin |              query              |         backend_type
-------+---------+-------+----------+----------+------------------+-------------+-----------------+-------------+-------------------------------+------------------------------+-------------------------------+-------------------------------+-----------------+---------------------+--------+-------------+--------------+---------------------------------+------------------------------
       |         |    88 |          |          |                  |             |                 |             | 2021-03-24 14:14:00.942297+02 |                              |                               |                               | Activity        | AutoVacuumMain      |        |             |              |                                 | autovacuum launcher
       |         |    90 |       10 | postgres |                  |             |                 |             | 2021-03-24 14:14:00.942908+02 |                              |                               |                               | Activity        | LogicalLauncherMain |        |             |              |                                 | logical replication launcher
 16403 | fdtdb   | 35030 |       10 | postgres | psql             | 10.0.0.2    |                 |       33334 | 2021-03-24 21:45:44.799218+02 | 2021-03-24 21:45:52.50269+02 | 2021-03-24 21:45:52.50269+02  | 2021-03-24 21:45:52.502692+02 |                 |                     | active |             |         1818 | select * from pg_stat_activity; | client backend
 16403 | fdtdb   |   220 |       10 | postgres |                  | 10.0.1.70   |                 |       50196 | 2021-03-24 14:14:16.958859+02 |                              | 2021-03-24 21:45:40.93202+02  | 2021-03-24 21:45:40.932112+02 | Client          | ClientRead          | idle   |             |              | select 1                        | client backend
 16403 | fdtdb   | 34380 |    16396 | pgrest   |                  | 10.0.1.70   |                 |       44008 | 2021-03-24 21:42:34.952121+02 |                              | 2021-03-24 21:45:51.590943+02 | 2021-03-24 21:45:51.594063+02 | Client          | ClientRead          | idle   |             |              | COMMIT                          | client backend
       |         |    86 |          |          |                  |             |                 |             | 2021-03-24 14:14:00.942726+02 |                              |                               |                               | Activity        | BgWriterHibernate   |        |             |              |                                 | background writer
       |         |    85 |          |          |                  |             |                 |             | 2021-03-24 14:14:00.941878+02 |                              |                               |                               | Activity        | CheckpointerMain    |        |             |              |                                 | checkpointer
       |         |    87 |          |          |                  |             |                 |             | 2021-03-24 14:14:00.942153+02 |                              |                               |                               | Activity        | WalWriterMain       |        |             |              |                                 | walwriter
(8 rows)
```

**Comment by diogob** [comment]
@W1M0R great stuff! It seems that we really need some sort of recovery for the `LISTEN` connection. I'll open a PR (probably next week) and we can continue the conversation there.

**Comment by W1M0R** [comment]
Thanks @diogob. I came across this stackoverflow answer: https://stackoverflow.com/a/8280281/755405

I'm not sure if `PGWS_POOL_SIZE` controls postgres connection pooling. If it does, then perhaps the reuse of connections might be a factor causing this issue.

**Comment by W1M0R** [comment]
I have seen the LISTEN session die under one of two conditions:

1. When there is no database activity on the channel for a few minutes (perhaps a timeout is in effect)
2. When the database is under severe load (due to stress tests and benchmarking)

It is unlikely that situation 2 will happen in our production setup, but it is very likely that situation 1 will happen.

**Comment by diogob** [comment]
@W1M0R I'm trying to reproduce the error by killing the back-end process that handles the PostgreSQL connection. The problem is that the postgresql client detects the failure on the back-end side and kills the connection, this shuts down postgres-websockets since we monitor the listener thread.

I have tried to reproduce using two methods:
* calling a pg_terminate_backend on my `LISTEN` connection.
  * in this case the server dies with `Broadcaster connection is dead`

* sending a `SIGKILL` directly to the connection process
  * in this case the server dies with `Broadcaster connection is dead`

* Using a `idle_in_transaction_session_timeout` GUC
  * In this case the connection is not affected since the LISTENER does not issue a `BEGIN` and the `LISTEN` works on the session.

I came with a hypothesis that might explain this, a middleware between postgres-websockets and your postgresql server could create this effect (by keeping the client connection alive and killing the server counterpart). Do you have any sort of connection pool external do postgres-websockets in place?

**Comment by W1M0R** [comment]
Thanks for your efforts in trying to understand the problem @diogob, it is very much appreciated. I am not aware of any middleware running. 

My setup runs nginx, postgres, PostgREST and postgres-websockets as services in a Docker swarm. The Docker Swarm runs on Ubuntu 20.04 inside a VirtualBox virtual machine created by Vagrant.  All the services run on the same machine. Only nginx is accessible by the outside world. The nginx service forwards requests from the outside world to the postgres-websockets service. The postgres-websockets service connects directly to postgres, without any middleware in between.

If any of the services fail, then Docker swarm restarts those services automatically. In order to overcome the issue I am having, I transformed your pg_stat_activity tip into a Docker healthcheck for the postgres-websocket.

This is an extract of the postgres-websockets service definition:

```yaml
  pgwebsockets:
    image: 127.0.0.1:5000/pgwebsockets:latest
    secrets:
      - postgres_db_uri
      - jwt_key
    environment:
      PGWS_DB_URI: "@/run/secrets/postgres_db_uri"
      PGWS_JWT_SECRET: "@/run/secrets/jwt_key"
      PGWS_LISTEN_CHANNEL: pgwebsockets
      PGWS_JWT_SECRET_BASE64: "False"
      PGWS_POOL_SIZE: 10
      PGWS_RETRIES: "6"
      HEALTH_QUERY: http://nginx/v1/health?select=ok:api_ws_events_channel_ok
      HEALTH_WANTED: '{"ok":true}'
      HEALTH_ACCEPT: application/vnd.pgrst.object+json
    ports:
      - "4567:3000"
    networks:
      - shared_network
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
    healthcheck:
      test: /docker-healthcheck.sh || exit 1
      start_period: 2s
      interval: 3s
      timeout: 10s
      retries: 1
```

The healthcheck script just calls a PostgREST function:

```bash
#!/usr/bin/env sh
set -eo pipefail
health_got=`wget --header="Accept: $HEALTH_ACCEPT" -O - -q $HEALTH_QUERY`
if [ "$health_got" = "$HEALTH_WANTED" ]; then 
    exit 0
fi
exit 1
```

The PostgREST function is implemented using the following SQL:

```sql
  select exists (select * from pg_stat_activity where datname = current_database() and query ilike 'listen%pgwebsockets%');
```

If there is no `listen pgwebsockets` entry in pg_stat_activity, then the healtcheck will fail, and Docker Swarm will restart postgres-websockets.

**Comment by diogob** [comment]
@W1M0R thanks for the details. I think that restoring the listener is a desirable feature anyways. So I'll go ahead and implement that. I'll leave it as configuration switch that can be turned off for cases where an external handler is desirable.

**Comment by diogob** [comment]
The latest release (0.11.0.0) should be able to handle this cases with the parameter `PGWS_CHECK_LISTENER_INTERVAL` that will monitor and re-spawn the listener connection.

**Comment by W1M0R** [comment]
PostgREST resolved a similar issue involving LISTEN: https://github.com/PostgREST/postgrest/issues/3147
