### ISSUE TITLE
Using the client-example with different URLs

### ISSUE THREAD

**Issue by fjf2002** [diogob/postgres-websockets#76]
Unfortunately, the client-example is hardcoded to port 3000 and path "/".

It won't work if I am using a different port or using a reverse-proxy that maps postgres-websockets to a path, say, for example, "/ws".

How about replacing client-example/client.js line 2-4 with something like:

```js
var uri = window.location.href.replace(/^http/, "ws").replace(/\/$/, "") + path;
```

(The first replaces http(s?) by ws(s?), the second replace deals with the case that href ends with a /.)

**Comment by diogob** [comment]
@fjf2002 I had the same issue a couple of days ago. Perhaps this should be open as an input for the user and I just set the default with the current value.
