### ISSUE TITLE
Wss connection Certificate

### ISSUE THREAD

**Issue by enzo-desimone** [diogob/postgres-websockets#82]
Hello,
I explain my situation to you. I have the websocket in a docker container on one server, which connects to another postgres server so not in localhost. I am trying to create a secure connection in order to use the wss protocol. Inserting the two variables (PGWS_CERTIFICATE_FILE && PGWS_KEY_FILE) the container starts without problems, but when I go to connect to the websocket it gives me this error 

`HandshakeFailed (Error_Packet_unexpected "Alert13 [(AlertLevel_Fatal,CertificateUnknown)]" " expected: handshake 13")`

**Comment by diogob** [comment]
@enzo-desimone the issue might be on the client side. It seems that the client does not recognize the CA used to sign the certificate. Have you made any further progress investigating this issue?

**Comment by enzo-desimone** [comment]
Unfortunately no

**Comment by diogob** [comment]
Could you send me more details on the websocket client? Also, could you send me more details about the certificate used? Hopefully with more details I would be able to reproduce this issue.

**Comment by diogob** [comment]
Feel free to reopen in case you have more details to help troubleshooting
