### ISSUE TITLE
Update alpine to 3.17 for libpq v15

### ISSUE THREAD

**Issue by wolfgangwalther** [diogob/postgres-websockets#89]
I'm trying to connect postgres-websockets with SSL client certificates in k8s. The SSL private key is owned by `root:postgres-websockets` with permissions 0440. Unfortunately it's not possible to change the owner of the mounted SSL private key without ugly hacks. root-owned private keys are only supported in libpq 15 since https://github.com/postgres/postgres/commit/a59c79564bdc209a5bc7b02d706f0d7352eb82fa.

Could you update the docker images to alpine 3.17, which includes libpq15?

Thanks!

**Comment by diogob** [comment]
@wolfgangwalther I have pushed new versions to dockerhub. I have just replaced the existing ones since there were no code changes.
