### ISSUE TITLE
Executable is not where documentation says it should be

### ISSUE THREAD

**Issue by elliottdehn** [diogob/postgres-websockets#93]
I have the following Dockerfile:

```dockerfile
FROM debian:stable-slim

RUN apt-get update \
    && apt-get install -y \
        libpq-dev \
        wget \
        git \
        build-essential \
        libffi-dev \
        libgmp-dev \
        zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root/.local/bin
ENV PATH="/root/.local/bin:$PATH"
WORKDIR /app
RUN wget -qO- https://get.haskellstack.org/ | sh
RUN git clone https://github.com/diogob/postgres-websockets.git
WORKDIR /app/postgres-websockets
RUN echo $HOME
RUN stack setup
RUN stack build
ENTRYPOINT ["/root/.local/bin/postgres-websockets"]
```

However, when I try to start it after building successfully, I get the following error: `docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/root/.local/bin/postgres-websockets": stat /root/.local/bin/postgres-websockets: no such file or directory: unknown`

The documentation both in the README of this repository and Stack both say the executable should be in `$HOME/.local/bin`. Indeed, I see `/root` where the `echo $HOME` is. This means the executable should be in `/root/.local/bin/postgres-websockets` but it is not.

I see this in the logs:
`#13 271.4 Installing executable postgres-websockets in /app/postgres-websockets/.stack-work/install/aarch64-linux-tinfo6/20de7113441220a7ce5fca1048d72e8e67b8d57630f11558ead82f270a85d24c/9.2.6/bin`... but this is not a stable or platform independent way to refer to the executable in question.

I need to compile from source so that the docker image resulting from build works for both Linux and Apple M1 machines. What might be going on here?

---

Right now to work-around I'm doing this:

```dockerfile
FROM debian:stable-slim

RUN apt-get update \
    && apt-get install -y \
        libpq-dev \
        wget \
        git \
        build-essential \
        libffi-dev \
        libgmp-dev \
        zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root/.local/bin
ENV PATH="/root/.local/bin:$PATH"
WORKDIR /app
RUN wget -qO- https://get.haskellstack.org/ | sh
RUN git clone https://github.com/diogob/postgres-websockets.git
WORKDIR /app/postgres-websockets
RUN echo $HOME
RUN stack setup
RUN stack build
RUN cd .stack-work/install/*/*/*/bin && mv * /root/.local/bin
ENTRYPOINT ["postgres-websockets"]
```

...but it's still not a stable way to address the executable (as stable as I could get it).

**Comment by diogob** [comment]
@elliottdehn thanks for opening the issue. I believe you caught a mistake in the README. The command `stack build` will not copy the binaries. You can use `stack install` instead (which is equivalent to `stack build --copy-bins`).

I'll update the README. Let me know if this fixes your problem.

**Comment by elliottdehn** [comment]
@diogob Oh interesting, thank you, glad I asked. So this works:

```dockerfile
FROM debian:stable-slim

RUN apt-get update \
    && apt-get install -y \
        libpq-dev \
        wget \
        git \
        build-essential \
        libffi-dev \
        libgmp-dev \
        zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

ENV PATH="/root/.local/bin:$PATH"
WORKDIR /app
RUN wget -qO- https://get.haskellstack.org/ | sh
RUN git clone https://github.com/diogob/postgres-websockets.git
WORKDIR /app/postgres-websockets
RUN stack setup
RUN stack install
ENTRYPOINT ["postgres-websockets"]
```

However, we'd like to pin as much as possible so that the build is stable. Therefore when trying to use a Haskell image as follows:

```dockerfile
FROM haskell:9.6-slim as builder

# Install System Dependencies
RUN apt-get update \
    && apt-get install -y \
        libpq-dev \
        wget \
        git \
        build-essential \
        libffi-dev \
        libgmp-dev \
        zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

# Clone the Repository
WORKDIR /app
RUN git clone https://github.com/diogob/postgres-websockets.git

# Build the Project
WORKDIR /app/postgres-websockets
RUN stack setup --verbose
RUN stack --system-ghc install --verbose

# Lightweight Final Image
FROM debian:bullseye-slim

# Install Runtime Dependencies
RUN apt-get update \
    && apt-get install -y \
        libpq-dev \
        libgmp-dev \
        zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy the Binary from the Builder
COPY --from=builder /root/.local/bin/postgres-websockets /usr/local/bin/postgres-websockets

# Set the Entry Point
ENTRYPOINT ["postgres-websockets"]
```

I get the following error:
```
 > [builder 7/7] RUN stack --system-ghc install --verbose:
1.601 2023-10-06 19:39:01.251675: [debug] Did not find shared library libtinfo.so.5
1.601 2023-10-06 19:39:01.251723: [debug] Found shared library libtinfo.so.6 in 'ldconfig -p' output
1.601 2023-10-06 19:39:01.251765: [debug] Found shared library libncursesw.so.6 in 'ldconfig -p' output
1.601 2023-10-06 19:39:01.251815: [debug] Found shared library libgmp.so.10 in 'ldconfig -p' output
1.601 2023-10-06 19:39:01.251892: [debug] Did not find shared library libgmp.so.3
1.601 2023-10-06 19:39:01.251935: [debug] Potential GHC builds: tinfo6-libc6-pre232, ncurses6
1.602 2023-10-06 19:39:01.252493: [debug] Found already installed GHC builds: 
1.602 2023-10-06 19:39:01.252736: [error] Error: [S-6362]
1.602 No compiler found, expected minor version match with ghc-9.2.6 (aarch64-tinfo6-libc6-pre232) (based on resolver setting in /app/postgres-websockets/stack.yaml).
1.602 To install the correct GHC into /root/.stack/programs/aarch64-linux/, try running 'stack setup' or use the '--install-ghc' flag. To use your system GHC installation, run 'stack config set system-ghc --global true', or use the '--system-ghc' flag.
```

As you can see, I'm using a haskell image and did both of its suggestions but I'm still getting the error. Perhaps you may know why I'm ironically getting issues with the Haskell image and not the Debian image?

**Comment by elliottdehn** [comment]
It looks like ghc `9.2.8` is stable and has an image: https://www.haskell.org/ghc/download.html, https://hub.docker.com/_/haskell/
But I don't see one for `9.2.6`. The image is `9.6`. Perhaps this has something to do with it?

**Comment by alnoki** [comment]
Noting here that we had to pin the resolver despite it being specified in `stack.yml`

```
FROM haskell:9.2.6-slim as builder

# ...

# Build the Project from source using the resolver it specifies
# https://github.com/diogob/postgres-websockets/tree/master#building-from-source
# https://github.com/diogob/postgres-websockets/blob/master/stack.yaml
WORKDIR /app/postgres-websockets
RUN stack setup
RUN stack install --resolver lts-20.12
```

**Comment by diogob** [comment]
@alnoki that is odd indeed.

Then second example (using the image `FROM haskell:9.2.6-slim as builder`) seems fine to me.

Also, have you tried the [published image](https://hub.docker.com/layers/diogob/postgres-websockets/latest/images/sha256-b952f6e1156585803a1a5d08feddb3b09c1164b2e4d92466ea89b63c2923857e?context=repo)

**Comment by diogob** [comment]
I have also upgraded the LTS version so we can compile with a more recent version of the toolchain.
Now it should use GHC 9.4.7 as the default compiler.

I have also published the latest release as a [docker image](https://hub.docker.com/layers/diogob/postgres-websockets/0.11.2.1/images/sha256-b2f2f63ea1817d8b53fc2149fdbcdd30a0d6c1a644d8769061549048835260c1?context=repo) and as a binary for ubuntu in the [github release page](https://github.com/diogob/postgres-websockets/releases/tag/0.11.2.1).

**Comment by alnoki** [comment]
@diogob we are not using the published image because we are building public infrastructure that needs to support a wide variety of architectures, hence we have adopted the policy of compilation from source 

We did end up pinning everything down, though: https://github.com/econia-labs/econia/blob/96b17a9/src/docker/api/Dockerfile.ws

Thanks for all of the back and forth on this, it has been helpful for us getting our WebSockets support set up

(Currently building on GCP artifact registry as I write this)
